import './globals.css'

export const metadata = {
  title: 'LoveBot 3000 Graph',
  description: 'Generated by create next app',
}

export default async function RootLayout(props: any) {
  
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>{props.children}</body>
    </html>
  )}
