import './globals.css'
import getData from './fetch.jsx'

export const metadata = {
  title: 'LoveBot 3000 Graph',
  description: 'Generated by create next app',
}

export default async function RootLayout(props: any) {

  props.params.data = await getData()
  props.params.foo = 'bar'

  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>{props.children}</body>
    </html>
  )}
