import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// export async function getInitialProps() {
//   const csvData = fs.createReadStream('./ranked-choice-vote.csv')
//   return {
//     props: {
//       csvData,
//     },
//   }
// }


export default function RootLayout(props: any) {

  // const csvData = fs.createReadStream('./ranked-choice-vote.csv')
  // const csvData = fs.readFileSync('./ranked-choice-vote.csv').toLocaleString()

  // const filePath = require('path').resolve(__dirname, './ranked-choice-vote.csv')
  // console.log(filePath)
  // const csvData = fs.readFileSync(filePath,'utf-8')
  // console.log(csvData)

  // const csvData = require('./ranked-choice-vote.csv')
  // console.log(csvData)

  // Papa.parse(csvData, {
  //   complete: (results) => {
  //     console.log(results)
  //     props.params.csvData = results
  //   }
  // })

  return (
    <html lang="en">
      <body>{props.children}</body>
    </html>
  )}

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   )
// }
